---
- name: Groep voor deployment aanmaken
  group: name=deploy state=present

- name: Deploy en Beheerder toevoegen
  user: name={{ item.name }} shell=/bin/bash state=present group=deploy comment="{{ item.comment }}"
  with_items:
    - { name: 'deploy', comment: 'Gebruikt om app te deployen' }
    - { name: 'beheerder', comment: 'Wheel user' }

- name: Let deploy own project root
  file: path={{path}} state=directory group=deploy

- name: GitHub public keys gebruiken voor inloggen
  authorized_key: user=deploy key="https://github.com/{{ item }}.keys"
  with_items:
    - rmens
    - marijnvdwerf

- name: Generate deploy key
  command: ssh-keygen -q  -t rsa -b 4096 -N ''  -f '/home/deploy/.ssh/id_rsa' creates=/home/deploy/.ssh/id_rsa

- shell: cat /home/deploy/.ssh/id_rsa.pub
  register: id_rsa_pub

- debug: msg="add the following key to https://github.com/omt/one-more-thing/settings/keys {{ id_rsa_pub.stdout }}"
