---

- name: Configure the New Relic apt repository.
  apt_repository: repo="deb http://apt.newrelic.com/debian/ newrelic non-free" state=present

- name: Trust the New Relic GPG key.
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: Update the local package list.
  apt: update_cache=yes

- name: Install the Server Monitor package
  apt: name=newrelic-sysmond state=present force=yes

- name: Add license key to config file
  shell: nrsysmond-config --set license_key="{{ newrelic_license_key }}"

- name: Ensure New Relic Sysmond is started and enabled
  service: name=newrelic-sysmond state=started enabled=yes

- apt: name=newrelic-php5 state=present force=yes

- command: newrelic-install install
  environment:
    NR_INSTALL_KEY: "{{ newrelic_license_key }}"
    NR_INSTALL_SILENT: yes

- lineinfile: dest=/etc/php5/apache2/conf.d/newrelic.ini regexp="newrelic.appname = " line='newrelic.appname = "{{ newrelic_app_name }}"' backup=yes
  notify: restart apache

- name: Disable New Relic on CLI
  lineinfile: dest=/etc/php5/cli/conf.d/newrelic.ini regexp="newrelic.enabled = " line='newrelic.enabled = false' backup=yes
