- name: Install Node.js
  apt: name=nodejs state=present force=yes
  
- name: Symink for nodejs to node
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  
- name: Install npm
  apt: name=npm state=present force=yes
  
- name: Install ruby
  apt: name=ruby state=present force=yes
  
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  
- name: install bundler
  gem: name=bundler state=latest user_install=no
  
- name: install bower
  npm: name=bower global=yes
  
- name: install grunt
  npm: name=grunt-cli global=yes

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: make composer executable
  file: path=/usr/local/bin/composer mode=a+x state=file