- name: Install Node.js
  apt: name=nodejs state=present force=yes
  
- name: Install npm
  apt: name=npm state=present force=yes
  
- name: Install ruby
  apt: name=ruby state=present force=yes
  
- name: Install Apache 2.4
  apt: name=apache2 state=present force=yes
  
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: make composer executable
  file: path=/usr/local/bin/composer mode=a+x state=file

- name: Disable default server
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache

- include: hhvm.yml
  when: hhvm

- include: php5.yml
  when: not hhvm

- name: Enable mod_rewrite
  apache2_module: state=present name=rewrite
  notify: restart apache

- name: Ensure root folder exists
  file: path={{path}} state=directory group=deploy mode="u=rwx,g=rs,o=rx"

- name: Enable server
  template: src=virtualhost.conf dest=/etc/apache2/sites-enabled/00-hamster.nl.conf owner=root group=root mode=644
  notify: restart apache
