- name: Install Apache 2.4
  apt: name=apache2 state=present force=yes

- name: Disable default server
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache

- name: Install PHP 5.6
  apt: name="{{ item }}" state=present force=yes
  with_items:
    - php5

- name: Enable OMT server
  copy: src=00-hamster.nl.conf dest=/etc/apache2/sites-enabled/00-hamster.nl.conf owner=root group=root mode=644
  notify: restart apache
