- name: Install Apache 2.4
  apt: name=apache2 state=present force=yes

- name: Install MySQL client
  apt: name=mysql-client state=present force=yes

- name: Disable default server
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache

- include: hhvm.yml
  when: hhvm

- include: php5.yml
  when: not hhvm
  
- include: deploytools.yml

- name: Enable mod_rewrite
  apache2_module: state=present name=rewrite
  notify: restart apache

- name: Ensure root folder exists
  file: path={{path}} state=directory mode="2775"

- name: Enable server
  template: src=virtualhost.conf dest=/etc/apache2/sites-enabled/00-hamster.nl.conf owner=root group=root mode=644
  notify: restart apache
