---
- name: Install PHP 5.6
  apt: name="{{ item }}" state=present force=yes
  with_items:
    - php5
    - php5-curl
    - php5-gd
    - php5-redis
    - php5-mysql
  notify: restart apache
    
- name: Add php.ini for CLI
  template: src=php.ini.j2 dest=/etc/php5/cli/php.ini owner=root group=root mode=644

- name: Remove memory limit for CLI
  ini_file: dest=/etc/php5/cli/php.ini section=PHP option=memory_limit value=-1

- name: Add php.ini for Apache
  template: src=php.ini.j2 dest=/etc/php5/apache2/php.ini owner=root group=root mode=644
  notify: restart apache

- name: Install Xdebug
  when: dev
  apt: name=php5-xdebug state=present
  notify: restart apache

- name: Enable Xdebug
  when: dev
  ini_file: dest=/etc/php5/apache2/php.ini section=xdebug option="{{ item.key }}" value="{{ item.value }}"
  with_dict:
    xdebug.remote_enable: on
    xdebug.remote_connect_back: on
  notify: restart apache

- name: Install NewRelic PHP deamon
  when: trackable
  apt: name=newrelic-php5 state=present force=yes

- command: newrelic-install install
  when: trackable
  environment:
    NR_INSTALL_KEY: "{{ newrelic_license_key }}"
    NR_INSTALL_SILENT: yes

- name: Set NewRelic app name
  when: trackable
  lineinfile: dest=/etc/php5/apache2/conf.d/newrelic.ini regexp="newrelic.appname = " line='newrelic.appname = "{{ newrelic_app_name }}"' backup=yes
  notify: restart apache

- name: Disable New Relic on CLI # TODO: Should this actually be disabled?
  when: trackable
  lineinfile: dest=/etc/php5/cli/conf.d/newrelic.ini regexp="newrelic.enabled = " line='newrelic.enabled = false' backup=yes
