---
- name: Install PHP 5.6
  apt: name="{{ item }}" state=present force=yes
  with_items:
    - php5

- name: Add php.ini for CLI
  template: src=php.ini.j2 dest=/etc/php5/cli/php.ini owner=root group=root mode=644

- name: Remove memory limit for CLI
  ini_file: dest=/etc/php5/cli/php.ini section=PHP option=memory_limit value=-1

- name: Add php.ini for Apache
  template: src=php.ini.j2 dest=/etc/php5/apache2/php.ini owner=root group=root mode=644
  notify: restart apache
