---
- name: Install PHP 5.6
  apt: name="{{ item }}" state=present force=yes
  with_items:
    - php5
    - php5-curl
    - php5-gd

- name: Add php.ini for CLI
  template: src=php.ini.j2 dest=/etc/php5/cli/php.ini owner=root group=root mode=644

- name: Remove memory limit for CLI
  ini_file: dest=/etc/php5/cli/php.ini section=PHP option=memory_limit value=-1

- name: Add php.ini for Apache
  template: src=php.ini.j2 dest=/etc/php5/apache2/php.ini owner=root group=root mode=644
  notify: restart apache

- name: Install Xdebug
  when: dev
  apt: name=php5-xdebug state=present
  notify: restart apache

- name: Enable Xdebug
  when: dev
  ini_file: dest=/etc/php5/apache2/php.ini section=xdebug option="{{ item.key }}" value="{{ item.value }}"
  with_dict:
    xdebug.remote_enable: on
    xdebug.remote_connect_back: on
  notify: restart apache
