---
- hosts: all
  vars_files:
    - ../private/ansible/vars.yml
  sudo: no
  user: root
  roles:
    - common

- hosts: web
  sudo: no
  user: root
  vars_files:
    - ../private/ansible/vars.yml
  roles:
    - web
    - deployable

- hosts: redis
  sudo: no
  user: root
  vars_files:
    - ../private/ansible/vars.yml
  roles:
    - redis

- hosts: database
  sudo: no
  user: root
  vars_files:
    - ../private/ansible/vars.yml
  roles:
    - database
