---
- hosts: all
  vars_files:
    - ../private/ansible/vars.yml
  sudo: no
  user: root
  roles:
    - common
    - trackable

- hosts: web
  sudo: no
  user: root
  vars_files:
    - ../private/ansible/vars.yml
  roles:
    - common
    - trackable
    - web
    - deployable
